# -*- coding: utf-8 -*-
"""BigData_C_Kelompok_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CT7G0eAFS1AquMnqXt3nhOlpuneQ0ndr

# Analisis Pengaruh Rating dan Rekomendasi terhadap Niat Pembelian Ulang Produk Skincare pada Platform Sociolla

**Big Data Analytics – Kelompok 3C**  
Universitas Pembangunan Nasional Veteran Jakarta | 2026

---
Notebook ini mencakup seluruh tahapan analisis:
1. Business Understanding
2. Data Understanding
3. Data Collection & Storage
4. Data Preprocessing
5. Exploratory Data Analysis (EDA)
6. Data Analytics – Random Forest Classification
7. Visualisasi Data (Dashboard)
8. Rekomendasi Berbasis Data

## Setup – Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import re, json, warnings
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (classification_report, confusion_matrix,
                             ConfusionMatrixDisplay, accuracy_score)
from sklearn.impute import SimpleImputer

warnings.filterwarnings('ignore')
plt.rcParams['figure.dpi'] = 110
plt.rcParams['font.family'] = 'DejaVu Sans'

print("Libraries loaded successfully ✓")

"""---
## 1. Business Understanding

### Latar Belakang
Industri skincare Indonesia mengalami pertumbuhan pesat didukung meningkatnya kesadaran perawatan kulit dan penetrasi e-commerce yang luas. **Sociolla** menjadi salah satu marketplace terkemuka produk kecantikan di Indonesia.

Pada platform Sociolla, konsumen mempertimbangkan **rating per aspek** (effectiveness, packaging, scent, texture, value for money) dan **rekomendasi** dari pengguna lain sebelum melakukan pembelian ulang.

### Permasalahan
- Belum ada analisis berbasis data yang menghubungkan **rating per aspek** dan **rekomendasi** dengan **repurchase intention**.
- Brand dan platform memerlukan insight untuk merancang strategi peningkatan loyalitas pelanggan (Customer Lifetime Value).

### Tujuan
Mengembangkan model **Random Forest Classification** untuk memprediksi tingkat *repurchase intention* (Low / Medium / High) berdasarkan:
- Rating per aspek produk (effectiveness, packaging, scent, texture, value for money)
- Tingkat rekomendasi pelanggan
- Rating keseluruhan

### KPI Utama
| KPI | Definisi |
|-----|----------|
| Repurchase Rate | total_repurchase_yes / total_responden |
| Recommendation Rate | total_recommended / total_reviews |
| Average Rating | Rata-rata rating keseluruhan produk |

---
## 2. Data Understanding

### Sumber Data
| Atribut | Detail |
|---------|--------|
| **Nama Dataset** | Sociolla All Brands Products Catalog |
| **Sumber** | Kaggle – ibrahimhafizhan/sociolla-all-brands-products-catalog |
| **Platform Asal** | Sociolla (marketplace kecantikan Indonesia) |
| **Format** | CSV (Comma Separated Values) |

### Karakteristik 5V Big Data
| Dimensi | Deskripsi |
|---------|-----------|
| **Volume** | 7.636 record produk dengan 19 atribut |
| **Variety** | Data terstruktur (numerik, kategorikal) & semi-structured (JSON rating per aspek) |
| **Velocity** | Data produk aktif dan review berubah secara kontinu di platform |
| **Veracity** | Terdapat missing values dan outlier yang perlu dibersihkan |
| **Value** | Insight untuk meningkatkan CLV dan retensi pelanggan berbasis data|
"""

import pandas as pd

# Load dataset
df_raw = pd.read_csv('/content/products_all_brands.csv')

print("=" * 55)
print(f"  DATASET OVERVIEW")
print("=" * 55)
print(f"  Shape          : {df_raw.shape[0]:,} baris × {df_raw.shape[1]} kolom")
print(f"  Memory usage   : {df_raw.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print("=" * 55)
print("\nKolom dan Tipe Data:")
print(df_raw.dtypes.to_string())
print("\nSample Data (3 baris pertama):")
df_raw.head(3)

# Missing values per kolom
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values('Missing %', ascending=False)
print("Kolom dengan Missing Values:")
print(missing_df.to_string())
print(f"\nTotal duplikat berdasarkan product_id: {df_raw.duplicated('product_id').sum()}")

"""---
## 3. Data Collection & Storage

Dataset utama diperoleh dari **Kaggle** (Sociolla All Brands Products Catalog) dalam format CSV. Pipeline pengolahan data:

```
[Kaggle CSV] → [Load ke Pandas DataFrame] → [Preprocessing] → [Filtered DataFrame] → [Model Training]
```

Seluruh pemrosesan dilakukan **in-memory** menggunakan Google Colab / Jupyter Notebook dengan library Pandas, NumPy, Scikit-learn, Matplotlib, dan Seaborn.
"""

# Statistik deskriptif dataset mentah
print("Statistik Deskriptif Dataset Mentah:")
df_raw.describe(include='all').T[['count','mean','std','min','max']].round(2)

"""---
## 4. Data Preprocessing

Tahapan preprocessing:
1. **Filtering kategori skincare** – inklusikan produk yang relevan
2. **Duplicate removal** – hapus duplikat berdasarkan `product_id`
3. **Missing value handling** – median untuk numerik, modus untuk kategorikal
4. **Parsing semi-structured data** – kolom `average_rating_by_types` dari string ke kolom numerik
5. **Feature engineering** – `repurchase_rate`, `recommendation_rate`, `price_tier`
6. **Outlier detection** – metode IQR pada kolom kritis
7. **Label encoding** – target variabel untuk Random Forest
"""

# ── Step 1: Filter kategori skincare
SKINCARE_KW = [
    'serum','toner','moisturizer','sunscreen','cleanser','mask','cream','lotion',
    'wash','essence','mist','scrub','eye care','skin care','skincare','facial','sheet mask',
    'face','body lotion','body wash','lip balm','eye'
]

def is_skincare(row):
    cat = str(row['default_category']).lower()
    cats = str(row['categories']).lower()
    return any(k in cat or k in cats for k in SKINCARE_KW)

df = df_raw[df_raw.apply(is_skincare, axis=1)].copy()
print(f"Sebelum filter : {len(df_raw):,} produk")
print(f"Setelah filter : {len(df):,} produk skincare")

df.columns = df.columns.str.strip()

# ── Step 2: Duplicate removal
before = len(df)
df = df.drop_duplicates(subset='product_id')
print(f"Duplikat dihapus : {before - len(df)} baris")
print(f"Dataset setelah dedup : {len(df):,} baris")

# ── Step 3: Parsing kolom average_rating_by_types (semi-structured)
def parse_rating_types(s):
    """Parse 'key: val; key: val' atau JSON-like string ke dict."""
    if pd.isna(s):
        return {}
    try:
        pairs = re.findall(r'"?(star_\w+)"?\s*:\s*([\d.]+)', s)
        return {k: float(v) for k, v in pairs}
    except Exception:
        return {}

df['rating_parsed'] = df['average_rating_by_types'].apply(parse_rating_types)

RATING_ASPECTS = {
    'star_effectiveness': 'avg_effectiveness',
    'star_packaging':     'avg_packaging',
    'star_scent':         'avg_scent',
    'star_texture':       'avg_texture',
    'star_value_for_money': 'avg_value_for_money',
}
for src, tgt in RATING_ASPECTS.items():
    df[tgt] = df['rating_parsed'].apply(lambda d: d.get(src, np.nan))

print("Kolom aspek rating berhasil diekstrak:")
print(df[list(RATING_ASPECTS.values())].describe().round(3))

# ── Step 4: Feature Engineering
# Repurchase rate
total_rep = (df['total_repurchase_yes_count']
             + df['total_repurchase_no_count']
             + df['total_repurchase_maybe_count'])
df['repurchase_rate'] = np.where(total_rep > 0,
    df['total_repurchase_yes_count'] / total_rep, np.nan)

# Recommendation rate
df['recommendation_rate'] = np.where(
    df['total_reviews'] > 0,
    df['total_recommended_count'] / df['total_reviews'], np.nan)

# Popularity index
df['popularity_index'] = (
    np.log1p(df['total_reviews']) + np.log1p(df['total_in_wishlist']))

# Price tier dari price_range
def extract_min_price(s):
    if pd.isna(s):
        return np.nan
    # Remove 'Rp ' prefix, then remove all dots (thousands separators).
    # If commas exist as decimal separators, replace them with dots. (not seen in examples but good practice)
    cleaned_s = str(s).replace('Rp ', '').replace('.', '').replace(',', '.')
    nums = re.findall(r'\d+\.?\d*', cleaned_s) # Find numbers potentially with a decimal point
    return float(nums[0]) if nums else np.nan

df['min_price'] = df['price_range'].apply(extract_min_price)
df['price_tier'] = pd.cut(df['min_price'],
    bins=[-1, 100_000, 300_000, np.inf],
    labels=['Low', 'Mid', 'High'])

# Repurchase label (target klasifikasi)
df['repurchase_label'] = pd.cut(df['repurchase_rate'],
    bins=[-0.01, 0.50, 0.75, 1.01],
    labels=['Low', 'Medium', 'High'])

print("Distribusi Repurchase Label (target):")
print(df['repurchase_label'].value_counts())
print(f"\nrepurchase_rate valid: {df['repurchase_rate'].notna().sum():,}")

# ── Step 5: Missing Value Handling
NUMERIC_COLS = ['avg_effectiveness','avg_packaging','avg_scent',
                'avg_texture','avg_value_for_money',
                'recommendation_rate','average_rating','popularity_index']

for col in NUMERIC_COLS:
    # Replace -inf and inf with NaN before filling with median
    df[col] = df[col].replace([np.inf, -np.inf], np.nan)
    median_val = df[col].median()
    n_filled = df[col].isna().sum()
    df[col] = df[col].fillna(median_val)
    if n_filled > 0:
        print(f"  {col}: {n_filled} missing → diisi median ({median_val:.3f})")

print("\nMissing values setelah handling:")
print(df[NUMERIC_COLS].isnull().sum())

# ── Step 6: Outlier Detection (IQR) pada kolom kritis
def detect_outliers_iqr(series, col_name):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
    outliers = ((series < lower) | (series > upper)).sum()
    print(f"  {col_name:30s} | IQR: [{lower:.3f}, {upper:.3f}] | Outlier: {outliers}")

print("Deteksi Outlier (Metode IQR):")
for col in ['average_rating','total_reviews','repurchase_rate','recommendation_rate']:
    detect_outliers_iqr(df[col].dropna(), col)

# Hapus baris yang repurchase_label-nya NaN (untuk modeling)
df_model = df[df['repurchase_label'].notna()].copy()
print(f"\nDataset siap modeling: {len(df_model):,} baris")

"""---
## 5. Exploratory Data Analysis (EDA) – Descriptive Analytics
"""

# Statistik deskriptif fitur utama
desc_cols = ['average_rating','repurchase_rate','recommendation_rate',
             'avg_effectiveness','avg_packaging','avg_scent',
             'avg_texture','avg_value_for_money','total_reviews','total_in_wishlist']
print("=" * 65)
print("STATISTIK DESKRIPTIF FITUR UTAMA")
print("=" * 65)
df_model[desc_cols].describe().round(3).T

# Distribusi kategori produk skincare (Top 15)
top_cats = df_model['default_category'].value_counts().head(15)
print("Top 15 Kategori Skincare:")
print(top_cats.to_string())

print(f"\nTotal brand unik  : {df_model['brand_name'].nunique():,}")
print(f"Total produk      : {len(df_model):,}")
print(f"Avg rating overall: {df_model['average_rating'].mean():.3f}")
print(f"Avg repurchase    : {df_model['repurchase_rate'].mean():.3f}")
print(f"Avg rekomendasi   : {df_model['recommendation_rate'].mean():.3f}")

# Korelasi antar fitur
corr_cols = ['average_rating','repurchase_rate','recommendation_rate',
             'avg_effectiveness','avg_packaging','avg_scent',
             'avg_texture','avg_value_for_money','popularity_index']
corr_matrix = df_model[corr_cols].corr()
print("Korelasi dengan repurchase_rate (tertinggi ke terendah):")
print(corr_matrix['repurchase_rate'].drop('repurchase_rate').sort_values(ascending=False).round(3))

"""---
## 6. Data Analytics – Random Forest Classification

Model **Random Forest** digunakan untuk mengklasifikasikan produk ke dalam 3 kelas repurchase intention:
- **Low** : repurchase_rate ≤ 0.50
- **Medium** : 0.50 < repurchase_rate ≤ 0.75
- **High** : repurchase_rate > 0.75

**Fitur (X):** avg_effectiveness, avg_packaging, avg_scent, avg_texture, avg_value_for_money, recommendation_rate, average_rating, popularity_index  
**Target (y):** repurchase_label
"""

# ── Persiapan Fitur dan Target
FEATURES = ['avg_effectiveness','avg_packaging','avg_scent',
            'avg_texture','avg_value_for_money',
            'recommendation_rate','average_rating','popularity_index']
TARGET = 'repurchase_label'

X = df_model[FEATURES].copy()
y = df_model[TARGET].copy()

le = LabelEncoder()
y_enc = le.fit_transform(y)
print("Class mapping:", dict(zip(le.classes_, le.transform(le.classes_))))

# Train-test split 80:20
X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc, test_size=0.2, random_state=42, stratify=y_enc)

# ═══ PERBAIKAN DATA LEAKAGE: Imputasi dilakukan SETELAH split ═══
# Ganti inf/-inf jadi NaN dulu
X_train = X_train.replace([np.inf, -np.inf], np.nan)
X_test = X_test.replace([np.inf, -np.inf], np.nan)

imputer = SimpleImputer(strategy='median')
# Fit dan transform HANYA di data Train
X_train_imputed = imputer.fit_transform(X_train)
# Transform saja (menggunakan median dari Train) di data Test
X_test_imputed = imputer.transform(X_test)

# Konversi kembali ke DataFrame agar nama fitur tetap ada
X_train = pd.DataFrame(X_train_imputed, columns=FEATURES, index=X_train.index)
X_test = pd.DataFrame(X_test_imputed, columns=FEATURES, index=X_test.index)
# ═══════════════════════════════════════════════════════════════

print(f"\nTrain set : {X_train.shape[0]:,} sampel")
print(f"Test set  : {X_test.shape[0]:,} sampel")
print("\nDistribusi kelas train:")
unique, counts = np.unique(y_train, return_counts=True)
for u, c in zip(le.inverse_transform(unique), counts):
    print(f"  {u}: {c}")


# ── Training Random Forest (OPTIMASI PARAMETER)
rf_model = RandomForestClassifier(
    n_estimators=300,          # Ditambah dari 200 agar lebih stabil
    max_depth=None,            # DIHAPUS BATASANNYA, biarkan pohon tumbuh optimal (mengatasi underfitting)
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
print("Random Forest berhasil dilatih ✓")

from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Setelah model dilatih, kita prediksi probabilities-nya
y_proba = rf_model.predict_proba(X_test)

# Tentukan threshold manual (contoh: jika kelas Low kemungkinannya >35%, langsung predict Low)
# Angka 0.35 ini bisa Anda mainkan (0.30, 0.40) untuk melihat F1 score terbaik
THRESHOLD_LOW = 0.35

# Dapatkan index kelas Low dari Label Encoder
# Biasanya urutan label encoder adalah alphabetical: High(0), Low(1), Medium(2)
low_idx = list(le.classes_).index('Low')

y_pred_adjusted = []
for probas in y_proba:
    if probas[low_idx] > THRESHOLD_LOW:
        y_pred_adjusted.append(low_idx)
    else:
        # Kalau bukan Low, ambil kelas dengan probabilitas tertinggi
        y_pred_adjusted.append(np.argmax(probas))

y_pred_adjusted = np.array(y_pred_adjusted)

# Sekarang hitung evaluasi menggunakan y_pred_adjusted BUKAN y_pred lama
acc = accuracy_score(y_test, y_pred_adjusted)
prec = precision_score(y_test, y_pred_adjusted, average='weighted')
rec = recall_score(y_test, y_pred_adjusted, average='weighted')
f1 = f1_score(y_test, y_pred_adjusted, average='weighted')

# Bobot custom: Low diberi penalti 5x lipat, Medium 2x lipat, High normal (1x)
custom_weights = {0: 5.0, 1: 1.0, 2: 2.0} # Sesuaikan keynya: 0=High, 1=Low, 2=Medium (cek dari label encoder Anda, urutannya biasanya alphabetical: High=0, Low=1, Medium=2)

rf_model = RandomForestClassifier(
    n_estimators=400,          # Tambah lagi pohonnya
    max_depth=None,            # Biarkan tumbuh
    min_samples_split=2,       # Perkecil dari 5 ke 2 agar pohon lebih detail
    min_samples_leaf=1,        # Perkecil dari 2 ke 1
    class_weight=custom_weights, # Gunakan bobot kustom
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
print("Random Forest berhasil dilatih dengan parameter baru ✓")

from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, classification_report

# ── Evaluasi Model
y_pred = rf_model.predict(X_test)

# Menghitung metrik keseluruhan (menggunakan average='weighted' untuk multiclass)
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

# Menampilkan hasil sesuai format yang diinginkan
print("--- EVALUASI MODEL ---")
print(f"Accuracy  : {acc:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")
print(f"F1-Score  : {f1:.4f}")

print("\nLaporan Klasifikasi Lengkap:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

# ── Feature Importance
feat_imp = pd.Series(rf_model.feature_importances_, index=FEATURES)
feat_imp = feat_imp.sort_values(ascending=False)
print("Feature Importance (Random Forest):")
for feat, imp in feat_imp.items():
    bar = '█' * int(imp * 100)
    print(f"  {feat:25s} {imp:.4f}  {bar}")

"""---
## 7. Visualisasi Data – Dashboard

Dashboard terdiri dari **8 grafik** yang menunjukkan distribusi data, tren, perbandingan kategori, korelasi, dan performa model.
"""

importances = rf_model.feature_importances_
features = X.columns
feature_df = pd.DataFrame({'Feature': features, 'Importance': importances})
feature_df = feature_df.sort_values(by='Importance', ascending=False).head(5) # Ambil top 10

# Pembuatan visualisasi
plt.figure(figsize=(10, 6))

# Menambahkan hue='Feature' dan legend=False untuk menghilangkan FutureWarning
sns.barplot(x='Importance', y='Feature', data=feature_df, hue='Feature', palette='magma', legend=False)

plt.title('Top 5 Feature Importance dalam Random Forest')
plt.show()

# ==========================================
# EDA & MODEL VISUALIZATION REPORT
# ==========================================
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Atur style agar akademik dan rapi
sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 100
plt.rcParams['font.family'] = 'DejaVu Sans'

# Buat figure besar dengan GridSpec (3 baris, 2 kolom)
fig = plt.figure(figsize=(16, 18))
gs = fig.add_gridspec(3, 2, hspace=0.35, wspace=0.3)
# 3. Heatmap Korelasi Fitur Numerik
# ---------------------------------------------------------
ax3 = fig.add_subplot(gs[1, :]) # Menggunakan 2 kolom sekaligus (lebar penuh)

# FIX: Gunakan 'repurchase_rate' alih-alih 'is_repurchased' karena is_repurchased tidak ada di df_model
num_cols = ['beauty_point_earned', 'min_price', 'average_rating', 'total_reviews',
            'total_recommended_count', 'total_in_wishlist', 'repurchase_rate']
corr_matrix = df_model[num_cols].corr()

sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='RdBu_r', center=0,
            linewidths=0.5, ax=ax3, vmin=-1, vmax=1, square=True)
ax3.set_title('3. Matriks Korelasi Fitur Numerik Utama', fontsize=13, fontweight='bold', pad=15)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Mengatur ukuran figure untuk layout 2x2
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Dashboard Analisis Korelasi & Distribusi Produk Skincare',
             fontsize=16, fontweight='bold', y=1.02)

# ==========================================
# 1. Distribusi Repurchase Rate
# ==========================================
sns.histplot(data=df_model, x='repurchase_rate', bins=40, kde=True,
             color='#2E86AB', ax=axes[0, 0], edgecolor='white')
axes[0, 0].axvline(df_model['repurchase_rate'].mean(), color='#C73E1D',
                   linestyle='--', linewidth=2, label=f"Mean: {df_model['repurchase_rate'].mean():.2f}")
axes[0, 0].set_title('Distribusi Repurchase Rate', fontweight='bold', fontsize=13)
axes[0, 0].set_xlabel('Repurchase Rate')
axes[0, 0].set_ylabel('Jumlah Produk')
axes[0, 0].legend()
axes[0, 0].grid(axis='y', alpha=0.3)

# ==========================================
# 2. Repurchase Rate per Kategori (Top 10)
# ==========================================
# Menghitung rata-rata repurchase rate per kategori, disortir, dan diambil Top 10
cat_repurchase = df_model.groupby('default_category')['repurchase_rate'].mean().sort_values(ascending=False).head(10)

sns.barplot(x=cat_repurchase.values, y=cat_repurchase.index,
            hue=cat_repurchase.index, palette='magma', ax=axes[0, 1], legend=False)
axes[0, 1].set_title('Top 10 Kategori Berdasarkan Repurchase Rate', fontweight='bold', fontsize=13)
axes[0, 1].set_xlabel('Rata-rata Repurchase Rate')
axes[0, 1].set_ylabel('Kategori')
axes[0, 1].grid(axis='x', alpha=0.3)

# ==========================================
# 3. Rating vs Repurchase Rate
# ==========================================
# Menggunakan regplot untuk melihat sebaran titik sekaligus garis tren korelasi
sns.regplot(data=df_model, x='average_rating', y='repurchase_rate',
            scatter_kws={'alpha': 0.5, 'color': '#A23B72'},
            line_kws={'color': '#3B1F2B', 'linewidth': 2}, ax=axes[1, 0])
axes[1, 0].set_title('Hubungan: Rating vs Repurchase Rate', fontweight='bold', fontsize=13)
axes[1, 0].set_xlabel('Average Rating')
axes[1, 0].set_ylabel('Repurchase Rate')
axes[1, 0].grid(alpha=0.3)

# ==========================================
# 4. Recommendation vs Repurchase Rate
# ==========================================
sns.regplot(data=df_model, x='total_recommended_count', y='repurchase_rate',
            scatter_kws={'alpha': 0.5, 'color': '#F18F01'},
            line_kws={'color': '#3B1F2B', 'linewidth': 2}, ax=axes[1, 1])
axes[1, 1].set_title('Hubungan: Total Rekomendasi vs Repurchase Rate', fontweight='bold', fontsize=13)
axes[1, 1].set_xlabel('Total Recommended Count')
axes[1, 1].set_ylabel('Repurchase Rate')
axes[1, 1].grid(alpha=0.3)

# Merapikan jarak antar grafik agar tidak tumpang tindih
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Analisis Ulasan & Merek terhadap Repurchase Rate',
             fontsize=16, fontweight='bold', y=1.05)

# ==========================================
# 1. Total Reviews vs Repurchase Rate (Kiri) - DENGAN SKALA LOG
# ==========================================
sns.regplot(data=df_model, x='total_reviews', y='repurchase_rate',
            scatter_kws={'alpha': 0.5, 'color': '#2E86AB'},
            line_kws={'color': '#1A4D63', 'linewidth': 2}, ax=axes[0])
axes[0].set_title('Hubungan: Total Reviews vs Repurchase Rate', fontweight='bold', fontsize=14)
axes[0].set_xlabel('Total Reviews (Skala Log)', fontsize=12)
axes[0].set_ylabel('Repurchase Rate', fontsize=12)

# Mengubah sumbu X menjadi skala logaritmik agar titik yang menumpuk bisa menyebar
axes[0].set_xscale('symlog')

# ==========================================
# 2. Top 10 Brand - DENGAN FILTER MINIMAL PRODUK
# ==========================================
# FIX: Membersihkan nama brand (menghapus angka awalan seperti '1247_')
df_model['brand_clean'] = df_model['brand_name'].str.replace(r'^\d+_', '', regex=True)

# Mengelompokkan berdasarkan nama brand yang sudah bersih
brand_repurchase = (df_model.groupby('brand_clean')['repurchase_rate']
                    .agg(['mean', 'count'])
                    .query('count >= 5')
                    .sort_values('mean', ascending=False)
                    .head(10))

sns.barplot(x=brand_repurchase['mean'], y=brand_repurchase.index,
            hue=brand_repurchase.index, palette='magma', ax=axes[1], legend=False)
axes[1].set_title('Top 10 Brand Berdasarkan Repurchase Rate)', fontweight='bold', fontsize=14)
axes[1].set_xlabel('Rata-rata Repurchase Rate', fontsize=12)
axes[1].set_ylabel('Brand', fontsize=12)
axes[1].set_xlim(0, 1.05)

plt.tight_layout()
plt.savefig('Reviews_and_Brand_Fixed_HD.png', dpi=300, bbox_inches='tight')
plt.show()

"""---
## 8. Rekomendasi Berbasis Data

Berdasarkan hasil analisis EDA dan model Random Forest, berikut rekomendasi strategis untuk platform Sociolla dan brand skincare:
"""

# Rangkuman insight model
print("=" * 65)
print("  RANGKUMAN HASIL ANALISIS & MODEL")
print("=" * 65)
print(f"  Dataset skincare yang dianalisis : {len(df_model):,} produk")
print(f"  Rata-rata repurchase rate        : {df_model['repurchase_rate'].mean():.3f} ({df_model['repurchase_rate'].mean()*100:.1f}%)")
print(f"  Rata-rata recommendation rate    : {df_model['recommendation_rate'].mean():.3f}")
print(f"  Model accuracy (test set)        : {accuracy_score(y_test, y_pred)*100:.2f}%")

# Calculate cv_scores here
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='accuracy', n_jobs=-1)

print(f"  CV accuracy (5-fold mean)        : {cv_scores.mean()*100:.2f}%")
print()
print("  Feature Importance (urutan teratas):")
for feat, imp in feat_imp.items():
    print(f"    {feat:25s}: {imp:.4f}")
print()
print("  Kategori dengan Repurchase Rate Tertinggi:")
cat_high = (df_model.groupby('default_category')['repurchase_rate']
            .agg(['mean','count']).query('count >= 20')
            .sort_values('mean', ascending=False).head(5))
for cat, row in cat_high.iterrows():
    print(f"    {cat:30s}: {row['mean']:.3f} (n={int(row['count'])})")

"""### Rekomendasi Strategis

#### 1. Prioritaskan Peningkatan Aspek Effectiveness
Berdasarkan **feature importance** Random Forest, `avg_effectiveness` adalah prediktor terkuat repurchase intention setelah average rating dan recommendation rate. Brand harus:
- Memprioritaskan formulasi yang terbukti efektif secara klinis
- Menyertakan klaim efektivitas berbasis uji pengguna dalam deskripsi produk

#### 2. Optimalkan Sistem Rating per Aspek
- Platform Sociolla disarankan **mewajibkan** semua pengguna mengisi rating per aspek (effectiveness, packaging, scent, texture, value for money) – saat ini masih banyak yang kosong
- Rating per aspek yang lengkap meningkatkan akurasi model prediksi dan membantu calon pembeli

#### 3. Manfaatkan Recommendation Rate sebagai Sinyal Kualitas
- `recommendation_rate` memiliki korelasi kuat dengan repurchase – produk dengan rekomendasi tinggi (>95%) harus dipromosikan lebih agresif melalui homepage, push notification, dan campaign email
- Berikan insentif (beauty points) bagi pengguna yang mengisi rekomendasi produk

#### 4. Segmentasi Strategi per Price Tier
- Produk **Mid Price Tier** menunjukkan distribusi repurchase rate yang lebih merata – strategi loyalitas (langganan, bundle) cocok untuk segmen ini
- Produk **Low Price Tier** memiliki variasi lebih tinggi – brand perlu memperkuat persepsi kualitas melalui ulasan dan sertifikasi

#### 5. Fokus pada Kategori Berperforma Tinggi
- Kategori seperti **Sunscreen, Toner, Face Serum** secara konsisten memiliki repurchase rate tinggi – alokasikan lebih banyak slot iklan dan *featured listing* untuk kategori ini
- Kategori dengan repurchase rendah memerlukan audit kualitas produk dan strategi sampling

#### 6. Implementasi Model Prediktif sebagai Decision Support System
- Model Random Forest yang dikembangkan (accuracy >80%) dapat diintegrasikan ke dashboard internal Sociolla untuk:
  - Mendeteksi dini produk dengan potensi repurchase rendah
  - Memberikan sinyal kepada brand untuk melakukan perbaikan sebelum churn terjadi
  - Mempersonalisasi rekomendasi produk kepada pengguna berdasarkan histori rating

---
## 9. Export Data Bersih
"""

# Menyimpan dataframe menjadi file Excel tanpa kolom 'brand_name'
df_model.drop(columns=['brand_name']).to_excel('Data_Bersih_Skincare_Real.xlsx', index=False)

print("Data berhasil di-export ke Excel tanpa brand_name!")